---
- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ openvpn_easyrsa_pki }}/configs"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Get certificate files
  ansible.builtin.slurp:
    src: "{{ path }}"
  loop:
  - "{{ openvpn_easyrsa_pki }}/ca.crt"
  - "{{ openvpn_easyrsa_pki }}/issued/{{ item.hostname }}.crt"
  - "{{ openvpn_easyrsa_pki }}/private/{{ item.hostname }}.key"
  loop_control:
    loop_var: path
    label: "{{ item }}"
  no_log: yes
  register: client_certs

- name: Render client configuration
  ansible.builtin.template:
    dest: "{{ openvpn_easyrsa_pki }}/configs/{{ item.hostname }}.ovpn"
    src: openvpn-client.ovpn.j2
    mode: '0400'
  vars:
    openvpn_client_ca: "{{ client_certs.results[0].content | b64decode }}"
    openvpn_client_cert: "{{ client_certs.results[1].content | b64decode }}"
    openvpn_client_key: "{{ client_certs.results[2].content | b64decode }}"
