---
- name: Run some sanity checks on variables
  ansible.builtin.assert:
    that:
    - openvpn_remote_protocol in ["tcp", "udp"]
    - openvpn_tls_auth in [True, False]

- name: Place dh.pem file
  when: openvpn_server_dhpem is defined
  ansible.builtin.copy:
    dest: "{{ openvpn_easyrsa_pki }}/dh.pem"
    content: "{{ openvpn_server_dhpem }}"
    mode: '0400'

- name: Generate Diffie Hellman parameters (will take at least 10 minutes)
  ansible.builtin.command: openssl dhparam -out "{{ openvpn_easyrsa_pki }}/dh.pem" -2 4096
  args:
    creates: "{{ openvpn_easyrsa_pki }}/dh.pem"

- name: TLS authentication
  when: openvpn_tls_auth
  block:
  - name: Generate TLS Auth parameters
    ansible.builtin.command: openvpn --genkey --secret "{{ openvpn_easyrsa_pki }}/ta.key"
    args:
      creates: "{{ openvpn_easyrsa_pki }}/ta.key"
  - name: Get TLS key
    ansible.builtin.slurp:
      src: "{{ openvpn_easyrsa_pki }}/ta.key"
    register: ta_key
